In [1]:
import re
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import string
import nltk
import warnings 

from sklearn.metrics.pairwise import cosine_similarity
warnings.filterwarnings("ignore", category=DeprecationWarning)

%matplotlib inline

In [2]:
data = pd.read_csv('android.csv', delimiter=",",engine='python', encoding='utf8')

In [3]:
data.head(20)

,Timestamp,Name,Email id,Institute,Graduation Type,Location,Department,Country,Skills,Lists your Projects/ Achievements,Number of Accomplishments
0,03-01-2022 17:28,Anjali Rawat,anjali27@gmail.com,KIIT,Undergraduate,Bhubaneshwar,Computer Science,India,Android Development,AI-Enabled FinTech B2B Invoice Management Appl...,3
1,03-01-2022 17:28,Harshal Gawas,harshalgaw@123,Tcet,Undergraduate,Mumbai,Information,India,Android Development,I am good in web development.. I like full sta...,4
2,03-01-2022 17:34,Saurav Telge,saurav@gmail.com,VESIT,Undergraduate,Mumbai,Computer,India,Android Development,DubML.AI-Our team proposes a system for dubbin...,6
3,03-01-2022 17:34,Samiksha Sachdeva,samiksha90@gmail.com,IIT Guwahati,Undergraduate,Guwahati,Computer Science,India,Android Development,\nCodeforces Crawler:- Worked on a Django-base...,4
4,03-01-2022 17:39,Jayesh Shah,jayeshshah123@mail.com,SAKEC,Undergraduate,Mumbai,Computer,India,Android Development,Certified in Android Application Development w...,5
5,03-01-2022 17:42,Sakshi Mehra,sakshi89@gmail.com,Panjab University,Undergraduate,Chandigarh,Electronics and Communications Engineering,India,Android Development,\nImplementation of machine learning algorithm...,2
6,03-01-2022 17:42,Shubham verma,sv@gmail.com,Sri Dadaji Institute of Technology & Science,Undergraduate,Nimar,Computer,NaN,Android Development,"4 years experience in Android Development, hav...",8
7,03-01-2022 17:47,Vrushali Mehta,vrushali97@gmail.com,DJS,Undergraduate,Mumbai,Computer Science,India,Android Development,E-Commerce Website:-Builted an E-Commerce Webs...,2
8,03-01-2022 17:48,Pratik Bhoir,pbhoir@gmail.com,University of Mumbai,Undergraduate,Mumbai,EXTC,India,Android Development,An Electronics & Telecommunication Engineer wh...,6
9,03-01-2022 17:53,manish malviya,mm@yahoo.com,S.N.P.I.T & RCumrakh.,Undergraduate,Pune,IT,India,Android Development,Experienced Android Developer with a demonstra...,4
10,03-01-2022 17:56,Rakesh Raushan,rakrau@gmail.com,SIES,Undergraduate,Nerul,Computer,India,Android Development,BlockChain|Cloud Computing|Full Stack Develope...,4
11,03-01-2022 17:59,Prachi Ray,prachi87@gmail.com,VIIT,Undergraduate,Mumbai,Computer Engineering,India,Android Development,Automated Product Recommender:- Builted this p...,3
12,03-01-2022 18:00,anurag shriniwar,anushri@hotmail.com,IIITH,Undergraduate,Hyderabad,Advanced Computing,India,Android Development,Did 5 projects\nElectronics and Telecommunicat...,6
13,03-01-2022 18:03,Ayush Kumar Singh,ayush23423@gmail.com,SRM University,Undergraduate,Chennai,Computer,India,Android Development,"7 projects, 4 internsips, 4 hackathons, won 3 ...",8
14,03-01-2022 18:03,Sparsh Mehta,sparch14@gmail.com,Chandigarh University,Undergraduate,Chandigarh,Computer Science,India,Android Development,Internship at MBK Health :- Artificial Develop...,5
15,03-01-2022 18:05,Shailesh Joisher,shaijoish@g.com,TCET,Undergraduate,Mumbai,Mechanical Engineering,India,Android Development,"5 projects, 2 hackathons, 3 winner\nIT Profess...",8
16,03-01-2022 18:07,Cyrus,cyrassasq@gmail.com,VIT,Undergraduate,Chennai,Computer,India,Android Development,Hybrid Multi-Cloud Computing\n3 projects\nProg...,3
17,03-01-2022 18:11,Gurleen Pannu,gkpannu15@gmail.com,Tcet,Undergraduate,Mumbai,Computer Science,India,Android Development,Rainfall Predictor:- Used various Algorithm un...,5
18,03-01-2022 18:13,Sudharma Mokashi,sudh@g.com,DY Patil,Undergraduate,Pune,Information Technology,India,Android Development,Cyber Security Enthusiast || Cloud Computing |...,4
19,03-01-2022 18:16,Gaurav Rajpal,gauraj@yahoo.com,Thakur College Of Engineering and tech,Undergraduate,Mumbai,AIML,India,Android Development,"4 intenrships, 3 projects, 2 internships\nChur...",6

In [4]:
data.drop('Timestamp', axis=1, inplace=True)

In [5]:
#input_text ->original text
#pattern -> pattern we want to remove
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
        
    return input_txt

In [6]:
# remove special characters, numbers, punctuations
data['cleaned_para'] = data['Lists your Projects/ Achievements'].str.replace("[^a-zA-Z]", " ")

<ipython-input-6-0562aad57c52>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data['cleaned_para'] = data['Lists your Projects/ Achievements'].str.replace("[^a-zA-Z]", " ")

In [7]:
data.head()

,Name,Email id,Institute,Graduation Type,Location,Department,Country,Skills,Lists your Projects/ Achievements,Number of Accomplishments,cleaned_para
0,Anjali Rawat,anjali27@gmail.com,KIIT,Undergraduate,Bhubaneshwar,Computer Science,India,Android Development,AI-Enabled FinTech B2B Invoice Management Appl...,3,AI Enabled FinTech B B Invoice Management Appl...
1,Harshal Gawas,harshalgaw@123,Tcet,Undergraduate,Mumbai,Information,India,Android Development,I am good in web development.. I like full sta...,4,I am good in web development I like full sta...
2,Saurav Telge,saurav@gmail.com,VESIT,Undergraduate,Mumbai,Computer,India,Android Development,DubML.AI-Our team proposes a system for dubbin...,6,DubML AI Our team proposes a system for dubbin...
3,Samiksha Sachdeva,samiksha90@gmail.com,IIT Guwahati,Undergraduate,Guwahati,Computer Science,India,Android Development,\nCodeforces Crawler:- Worked on a Django-base...,4,Codeforces Crawler Worked on a Django based...
4,Jayesh Shah,jayeshshah123@mail.com,SAKEC,Undergraduate,Mumbai,Computer,India,Android Development,Certified in Android Application Development w...,5,Certified in Android Application Development w...

In [8]:
# remove short words
data['cleaned_para'] = data['cleaned_para'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>3]))

In [9]:
data.head()

,Name,Email id,Institute,Graduation Type,Location,Department,Country,Skills,Lists your Projects/ Achievements,Number of Accomplishments,cleaned_para
0,Anjali Rawat,anjali27@gmail.com,KIIT,Undergraduate,Bhubaneshwar,Computer Science,India,Android Development,AI-Enabled FinTech B2B Invoice Management Appl...,3,Enabled FinTech Invoice Management Application...
1,Harshal Gawas,harshalgaw@123,Tcet,Undergraduate,Mumbai,Information,India,Android Development,I am good in web development.. I like full sta...,4,good development like full stack which include...
2,Saurav Telge,saurav@gmail.com,VESIT,Undergraduate,Mumbai,Computer,India,Android Development,DubML.AI-Our team proposes a system for dubbin...,6,DubML team proposes system dubbing videos from...
3,Samiksha Sachdeva,samiksha90@gmail.com,IIT Guwahati,Undergraduate,Guwahati,Computer Science,India,Android Development,\nCodeforces Crawler:- Worked on a Django-base...,4,Codeforces Crawler Worked Django based website...
4,Jayesh Shah,jayeshshah123@mail.com,SAKEC,Undergraduate,Mumbai,Computer,India,Android Development,Certified in Android Application Development w...,5,Certified Android Application Development with...

In [10]:
tokenized_data = data['cleaned_para'].apply(lambda x: x.split())

In [11]:
tokenized_data.head()

0    [Enabled, FinTech, Invoice, Management, Applic...
1    [good, development, like, full, stack, which, ...
2    [DubML, team, proposes, system, dubbing, video...
3    [Codeforces, Crawler, Worked, Django, based, w...
4    [Certified, Android, Application, Development,...
Name: cleaned_para, dtype: object

In [12]:
# stemming (play, players etc to play)
from nltk.stem.porter import *
stemmer = PorterStemmer()

tokenized_data = tokenized_data.apply(lambda x: [stemmer.stem(i) for i in x]) # stemming

In [13]:
tokenized_data.head()

0    [enabl, fintech, invoic, manag, applic, applic...
1    [good, develop, like, full, stack, which, incl...
2    [dubml, team, propos, system, dub, video, from...
3    [codeforc, crawler, work, django, base, websit...
4    [certifi, android, applic, develop, with, over...
Name: cleaned_para, dtype: object

In [14]:
data.head()

,Name,Email id,Institute,Graduation Type,Location,Department,Country,Skills,Lists your Projects/ Achievements,Number of Accomplishments,cleaned_para
0,Anjali Rawat,anjali27@gmail.com,KIIT,Undergraduate,Bhubaneshwar,Computer Science,India,Android Development,AI-Enabled FinTech B2B Invoice Management Appl...,3,Enabled FinTech Invoice Management Application...
1,Harshal Gawas,harshalgaw@123,Tcet,Undergraduate,Mumbai,Information,India,Android Development,I am good in web development.. I like full sta...,4,good development like full stack which include...
2,Saurav Telge,saurav@gmail.com,VESIT,Undergraduate,Mumbai,Computer,India,Android Development,DubML.AI-Our team proposes a system for dubbin...,6,DubML team proposes system dubbing videos from...
3,Samiksha Sachdeva,samiksha90@gmail.com,IIT Guwahati,Undergraduate,Guwahati,Computer Science,India,Android Development,\nCodeforces Crawler:- Worked on a Django-base...,4,Codeforces Crawler Worked Django based website...
4,Jayesh Shah,jayeshshah123@mail.com,SAKEC,Undergraduate,Mumbai,Computer,India,Android Development,Certified in Android Application Development w...,5,Certified Android Application Development with...

In [15]:
#replacing new with result
for i in range(len(tokenized_data)):
    tokenized_data[i] = ' '.join(tokenized_data[i])

data['cleaned_para'] = tokenized_data

In [16]:
data.head()

,Name,Email id,Institute,Graduation Type,Location,Department,Country,Skills,Lists your Projects/ Achievements,Number of Accomplishments,cleaned_para
0,Anjali Rawat,anjali27@gmail.com,KIIT,Undergraduate,Bhubaneshwar,Computer Science,India,Android Development,AI-Enabled FinTech B2B Invoice Management Appl...,3,enabl fintech invoic manag applic applic desig...
1,Harshal Gawas,harshalgaw@123,Tcet,Undergraduate,Mumbai,Information,India,Android Development,I am good in web development.. I like full sta...,4,good develop like full stack which includ html...
2,Saurav Telge,saurav@gmail.com,VESIT,Undergraduate,Mumbai,Computer,India,Android Development,DubML.AI-Our team proposes a system for dubbin...,6,dubml team propos system dub video from englis...
3,Samiksha Sachdeva,samiksha90@gmail.com,IIT Guwahati,Undergraduate,Guwahati,Computer Science,India,Android Development,\nCodeforces Crawler:- Worked on a Django-base...,4,codeforc crawler work django base websit scrap...
4,Jayesh Shah,jayeshshah123@mail.com,SAKEC,Undergraduate,Mumbai,Computer,India,Android Development,Certified in Android Application Development w...,5,certifi android applic develop with overal yea...

In [17]:
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer(max_df=0.95, min_df=2, max_features=1000, stop_words='english')
# bag-of-words feature matrix
bow = bow_vectorizer.fit_transform(data['cleaned_para'])

In [18]:
bow

<26x306 sparse matrix of type '<class 'numpy.int64'>'
	with 1029 stored elements in Compressed Sparse Row format>

In [19]:
pd.DataFrame(bow.todense()).head()

,0,1,2,3,4,5,6,7,8,9,...,296,297,298,299,300,301,302,303,304,305
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,2,0,0,0,0,0,0,0,...,0,0,2,0,1,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
4,5,2,0,0,0,0,0,0,0,0,...,2,0,5,0,0,0,2,0,0,3

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
# TF-IDF feature matrix
tfidf = tfidf_vectorizer.fit_transform(data['cleaned_para'])

In [21]:
pd.DataFrame(tfidf.todense()).head(25)

,0,1,2,3,4,5,6,7,8,9,...,296,297,298,299,300,301,302,303,304,305
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.13783,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.085292,0.187451,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.146813,0.000000,0.073406,0.000000,0.055638,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.159056,0.000000,0.120555,0.000000,0.000000,0.000000
4,0.097636,0.035540,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.039054,0.000000,0.076469,0.000000,0.000000,0.000000,0.023184,0.000000,0.000000,0.049222
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.399066,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.16251,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.147888,0.127279,0.000000,0.000000,0.000000,0.048235,0.000000,0.000000,0.136546
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.472879,0.000000,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.128360,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.152394,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.087617,0.000000,0.262852,0.000000,0.099613,0.000000,0.000000,0.000000
10,0.127800,0.232602,0.000000,0.058151,0.000000,0.00000,0.000000,0.000000,0.000000,0.063900,...,0.000000,0.000000,0.000000,0.058151,0.000000,0.063900,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.217544,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.154852,0.000000,0.000000,0.000000,0.000000,0.000000,0.091924,0.000000,0.000000,0.130111
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.074396,0.000000,...,0.000000,0.000000,0.058267,0.000000,0.000000,0.000000,0.044163,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.355092,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
15,0.000000,0.000000,0.000000,0.079516,0.000000,0.00000,0.000000,0.087378,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.087378,0.000000,0.000000,0.000000,0.073417
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.115414,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.068512,0.000000,0.115414,0.000000
17,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.172909,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,0.000000,0.000000,0.294186,0.041187,0.000000,0.00000,0.156875,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,0.000000,0.000000,0.000000,0.000000,0.184770,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.336289,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,0.000000,0.000000,0.000000,0.000000,0.110253,0.00000,0.038215,0.000000,0.000000,0.000000,...,0.000000,0.050166,0.000000,0.000000,0.043175,0.000000,0.163622,0.110253,0.055127,0.000000
22,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.365327,0.000000,0.000000,0.263498,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.059089,0.000000,0.177267,0.000000,0.000000,0.000000,0.064932,0.000000,0.000000

In [22]:
# generating the cosine similarity matrix
cosine_sim = cosine_similarity(tfidf, tfidf)

In [23]:
cosine_sim

array([[1.        , 0.02532261, 0.10405002, 0.21483458, 0.32935577,
        0.0659114 , 0.08071277, 0.02752067, 0.08167296, 0.16944636,
        0.18918225, 0.01430398, 0.17981036, 0.12141442, 0.02038002,
        0.10733383, 0.05076405, 0.02273833, 0.16611696, 0.0796907 ,
        0.08141889, 0.05224795, 0.05258145, 0.11345417, 0.08339246,
        0.19967055],
       [0.02532261, 1.        , 0.22945824, 0.09204364, 0.05907374,
        0.        , 0.09805373, 0.21212948, 0.12564694, 0.06199055,
        0.13210833, 0.06377702, 0.09979291, 0.04526645, 0.08067111,
        0.04654568, 0.04621959, 0.06547734, 0.06501719, 0.05825446,
        0.        , 0.04345296, 0.08507134, 0.        , 0.02051501,
        0.12574059],
       [0.10405002, 0.22945824, 1.        , 0.08941541, 0.09919277,
        0.08845538, 0.2129429 , 0.09337772, 0.15181866, 0.12733151,
        0.11394908, 0.04411171, 0.14978011, 0.19871923, 0.01438428,
        0.0941272 , 0.03198792, 0.02801729, 0.10234198, 0.16558647,
        0.04939307, 0.10154949, 0.08522237, 0.02362076, 0.16457798,
        0.05423275],
       [0.21483458, 0.09204364, 0.08941541, 1.        , 0.16132012,
        0.12634349, 0.17227839, 0.16653618, 0.03863528, 0.19285957,
        0.05396353, 0.06606884, 0.06135526, 0.12108324, 0.01720096,
        0.05583017, 0.05140054, 0.03350353, 0.13358848, 0.11276623,
        0.05130974, 0.07582402, 0.07279468, 0.        , 0.07986213,
        0.        ],
       [0.32935577, 0.05907374, 0.09919277, 0.16132012, 1.        ,
        0.00940937, 0.33055731, 0.01013099, 0.21712959, 0.17529567,
        0.43543037, 0.0958209 , 0.21585384, 0.17373588, 0.16036629,
        0.18346237, 0.08340262, 0.03370009, 0.1866381 , 0.18343984,
        0.03447639, 0.08640763, 0.06666021, 0.06697384, 0.0784614 ,
        0.08287348],
       [0.0659114 , 0.        , 0.08845538, 0.12634349, 0.00940937,
        1.        , 0.03093795, 0.07619055, 0.10087678, 0.01749002,
        0.01978082, 0.2601558 , 0.06289593, 0.1033353 , 0.23454384,
        0.06729254, 0.04065798, 0.3148509 , 0.08360609, 0.18203762,
        0.08456448, 0.16429688, 0.21380837, 0.08779007, 0.16797205,
        0.        ],
       [0.08071277, 0.09805373, 0.2129429 , 0.17227839, 0.33055731,
        0.03093795, 1.        , 0.09015248, 0.12811246, 0.11529212,
        0.22348679, 0.1209548 , 0.21842436, 0.12962068, 0.06069869,
        0.13346499, 0.05731199, 0.04109378, 0.17188625, 0.18556086,
        0.09445967, 0.04424903, 0.16719013, 0.01114748, 0.0646332 ,
        0.12676787],
       [0.02752067, 0.21212948, 0.09337772, 0.16653618, 0.01013099,
        0.07619055, 0.09015248, 1.        , 0.        , 0.15820037,
        0.01275903, 0.15670801, 0.01545975, 0.09509125, 0.08612738,
        0.01424983, 0.04916632, 0.10287235, 0.02268036, 0.04848116,
        0.06092545, 0.03345121, 0.        , 0.        , 0.06260368,
        0.        ],
       [0.08167296, 0.12564694, 0.15181866, 0.03863528, 0.21712959,
        0.10087678, 0.12811246, 0.        , 1.        , 0.12933815,
        0.16434916, 0.0912413 , 0.21981038, 0.09733144, 0.06425062,
        0.0723697 , 0.05826074, 0.03438877, 0.09138413, 0.10062406,
        0.01273717, 0.11669051, 0.14148497, 0.05585706, 0.11945826,
        0.21510527],
       [0.16944636, 0.06199055, 0.12733151, 0.19285957, 0.17529567,
        0.01749002, 0.11529212, 0.15820037, 0.12933815, 1.        ,
        0.2472341 , 0.06834414, 0.08927571, 0.18400786, 0.0182464 ,
        0.08908527, 0.14172019, 0.03251757, 0.16148326, 0.11228198,
        0.0255167 , 0.13996766, 0.072305  , 0.07054004, 0.07672505,
        0.13910582],
       [0.18918225, 0.13210833, 0.11394908, 0.05396353, 0.43543037,
        0.01978082, 0.22348679, 0.01275903, 0.16434916, 0.2472341 ,
        1.        , 0.15531696, 0.2705183 , 0.1195077 , 0.05269988,
        0.18422696, 0.18972217, 0.01054186, 0.27893884, 0.18347366,
        0.12640145, 0.15574165, 0.17276381, 0.06573082, 0.10643268,
        0.10793564],
       [0.01430398, 0.06377702, 0.04411171, 0.06606884, 0.0958209 ,
        0.2601558 , 0.1209548 , 0.15670801, 0.0912413 , 0.06834414,
        0.15531696, 1.        , 0.03620645, 0.18496739, 0.44999656,
        0.06841431, 0.11021625, 0.45734072, 0.09550791, 0.35671633,
        0.26057186, 0.34146415, 0.23399719, 0.21230327, 0.18724691,
        0.09485367],
       [0.17981036, 0.09979291, 0.14978011, 0.06135526, 0.21585384,
        0.06289593, 0.21842436, 0.01545975, 0.21981038, 0.08927571,
        0.2705183 , 0.03620645, 1.        , 0.15109885, 0.03342632,
        0.40944009, 0.17219895, 0.01277327, 0.20883478, 0.09430146,
        0.02321191, 0.14731687, 0.26494197, 0.08310814, 0.07082381,
        0.09585123],
       [0.12141442, 0.04526645, 0.19871923, 0.12108324, 0.17373588,
        0.1033353 , 0.12962068, 0.09509125, 0.09733144, 0.18400786,
        0.1195077 , 0.18496739, 0.15109885, 1.        , 0.05425718,
        0.06678559, 0.13314119, 0.08053779, 0.11346356, 0.18560548,
        0.15510605, 0.07840305, 0.13726623, 0.03911996, 0.1997647 ,
        0.09892515],
       [0.02038002, 0.08067111, 0.01438428, 0.01720096, 0.16036629,
        0.23454384, 0.06069869, 0.08612738, 0.06425062, 0.0182464 ,
        0.05269988, 0.44999656, 0.03342632, 0.05425718, 1.        ,
        0.        , 0.01217778, 0.34358667, 0.06490409, 0.29648836,
        0.18299015, 0.18757964, 0.17607816, 0.26365623, 0.09068668,
        0.05101133],
       [0.10733383, 0.04654568, 0.0941272 , 0.05583017, 0.18346237,
        0.06729254, 0.13346499, 0.01424983, 0.0723697 , 0.08908527,
        0.18422696, 0.06841431, 0.40944009, 0.06678559, 0.        ,
        1.        , 0.12749266, 0.        , 0.12284285, 0.13789149,
        0.01553859, 0.16605078, 0.17423423, 0.04929972, 0.03372945,
        0.05485196],
       [0.05076405, 0.04621959, 0.03198792, 0.05140054, 0.08340262,
        0.04065798, 0.05731199, 0.04916632, 0.05826074, 0.14172019,
        0.18972217, 0.11021625, 0.17219895, 0.13314119, 0.01217778,
        0.12749266, 1.        , 0.00952012, 0.30757854, 0.06067765,
        0.12658606, 0.24021207, 0.23375361, 0.11447216, 0.05205298,
        0.09621911],
       [0.02273833, 0.06547734, 0.02801729, 0.03350353, 0.03370009,
        0.3148509 , 0.04109378, 0.10287235, 0.03438877, 0.03251757,
        0.01054186, 0.45734072, 0.01277327, 0.08053779, 0.34358667,
        0.        , 0.00952012, 1.        , 0.04322558, 0.28640857,
        0.07147329, 0.16111326, 0.09239708, 0.15248997, 0.17413481,
        0.        ],
       [0.16611696, 0.06501719, 0.10234198, 0.13358848, 0.1866381 ,
        0.08360609, 0.17188625, 0.02268036, 0.09138413, 0.16148326,
        0.27893884, 0.09550791, 0.20883478, 0.11346356, 0.06490409,
        0.12284285, 0.30757854, 0.04322558, 1.        , 0.15665619,
        0.00672043, 0.11189439, 0.2785855 , 0.07369981, 0.07575894,
        0.08670424],
       [0.0796907 , 0.05825446, 0.16558647, 0.11276623, 0.18343984,
        0.18203762, 0.18556086, 0.04848116, 0.10062406, 0.11228198,
        0.18347366, 0.35671633, 0.09430146, 0.18560548, 0.29648836,
        0.13789149, 0.06067765, 0.28640857, 0.15665619, 1.        ,
        0.19120103, 0.15170349, 0.26263057, 0.07244068, 0.28270202,
        0.14395535],
       [0.08141889, 0.        , 0.04939307, 0.05130974, 0.03447639,
        0.08456448, 0.09445967, 0.06092545, 0.01273717, 0.0255167 ,
        0.12640145, 0.26057186, 0.02321191, 0.15510605, 0.18299015,
        0.01553859, 0.12658606, 0.07147329, 0.00672043, 0.19120103,
        1.        , 0.28408933, 0.08860416, 0.08703073, 0.25363042,
        0.05228181],
       [0.05224795, 0.04345296, 0.10154949, 0.07582402, 0.08640763,
        0.16429688, 0.04424903, 0.03345121, 0.11669051, 0.13996766,
        0.15574165, 0.34146415, 0.14731687, 0.07840305, 0.18757964,
        0.16605078, 0.24021207, 0.16111326, 0.11189439, 0.15170349,
        0.28408933, 1.        , 0.31221881, 0.32356743, 0.36547461,
        0.0989526 ],
       [0.05258145, 0.08507134, 0.08522237, 0.07279468, 0.06666021,
        0.21380837, 0.16719013, 0.        , 0.14148497, 0.072305  ,
        0.17276381, 0.23399719, 0.26494197, 0.13726623, 0.17607816,
        0.17423423, 0.23375361, 0.09239708, 0.2785855 , 0.26263057,
        0.08860416, 0.31221881, 1.        , 0.06205685, 0.1266432 ,
        0.19449645],
       [0.11345417, 0.        , 0.02362076, 0.        , 0.06697384,
        0.08779007, 0.01114748, 0.        , 0.05585706, 0.07054004,
        0.06573082, 0.21230327, 0.08310814, 0.03911996, 0.26365623,
        0.04929972, 0.11447216, 0.15248997, 0.07369981, 0.07244068,
        0.08703073, 0.32356743, 0.06205685, 1.        , 0.14765732,
        0.        ],
       [0.08339246, 0.02051501, 0.16457798, 0.07986213, 0.0784614 ,
        0.16797205, 0.0646332 , 0.06260368, 0.11945826, 0.07672505,
        0.10643268, 0.18724691, 0.07082381, 0.1997647 , 0.09068668,
        0.03372945, 0.05205298, 0.17413481, 0.07575894, 0.28270202,
        0.25363042, 0.36547461, 0.1266432 , 0.14765732, 1.        ,
        0.10733381],
       [0.19967055, 0.12574059, 0.05423275, 0.        , 0.08287348,
        0.        , 0.12676787, 0.        , 0.21510527, 0.13910582,
        0.10793564, 0.09485367, 0.09585123, 0.09892515, 0.05101133,
        0.05485196, 0.09621911, 0.        , 0.08670424, 0.14395535,
        0.05228181, 0.0989526 , 0.19449645, 0.        , 0.10733381,
        1.        ]])

In [24]:
data['Lists your Projects/ Achievements'][0]

'AI-Enabled FinTech B2B Invoice Management Application:- A web application designed using ReactJS, Java, MySQL, Python for the AR analysts to manage invoices of customers with an integrated Professor ChatBot created using Dialogflow and an ML model to predict the partial payment of customers, \nMess Management Application:- A Hostel Mess Management Application based on Android, Java, NoSql, and Firebase. The application will replace the traditional mess system of our university. Students can track mess menu, give feedbacks and set up reminders. Admin can track student feedbacks and regularly update mess menu.\nPerformed a key role in the development process of the UI portion of the mobile application.\n'

In [25]:
print("recommendation for")
index=12
print(data["Skills"][index])
print("-------------")
a=cosine_sim[index]
print(a)
s=np.argsort(a)[::-1]
print(s)
s=s[a[s]>0.15]


for i in s[1:]:
    print(data["Name"][i])
    print(i)
    print('|||')

recommendation for
Android Development
-------------
[0.17981036 0.09979291 0.14978011 0.06135526 0.21585384 0.06289593
 0.21842436 0.01545975 0.21981038 0.08927571 0.2705183  0.03620645
 1.         0.15109885 0.03342632 0.40944009 0.17219895 0.01277327
 0.20883478 0.09430146 0.02321191 0.14731687 0.26494197 0.08310814
 0.07082381 0.09585123]
[12 15 10 22  8  6  4 18  0 16 13  2 21  1 25 19  9 23 24  5  3 11 14 20
  7 17]
Shailesh Joisher
15
|||
Rakesh Raushan
10
|||
Tanish Balsara
22
|||
Pratik Bhoir
8
|||
Shubham verma
6
|||
Jayesh Shah
4
|||
Sudharma Mokashi
18
|||
Anjali Rawat
0
|||
Cyrus
16
|||
Ayush Kumar Singh
13
|||